//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacklogConvertData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Trans {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Trans() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BacklogConvertData.Properties.Trans", typeof(Trans).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データのインポートは失敗しました。.
        /// </summary>
        internal static string Data_import_failed {
            get {
                return ResourceManager.GetString("Data import failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データはバックログに正常にインポートされます。.
        /// </summary>
        internal static string Data_import_to_backlog_successfully {
            get {
                return ResourceManager.GetString("Data import to backlog successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to インポートファイルを開くエラー。.
        /// </summary>
        internal static string Error_opening_import_file {
            get {
                return ResourceManager.GetString("Error opening import file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルが見つかりません。.
        /// </summary>
        internal static string File_not_found {
            get {
                return ResourceManager.GetString("File not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルをインポートしないデータは存在しません。.
        /// </summary>
        internal static string Import_file_don_t_exist_data {
            get {
                return ResourceManager.GetString("Import file don\'t exist data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to インポートファイルはExcel形式である必要があります。.
        /// </summary>
        internal static string Import_file_must_be_an_excel_format {
            get {
                return ResourceManager.GetString("Import file must be an excel format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロジェクトを選択してください。.
        /// </summary>
        internal static string Please_select_a_project {
            get {
                return ResourceManager.GetString("Please select a project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーを選択してください。.
        /// </summary>
        internal static string Please_select_an_user {
            get {
                return ResourceManager.GetString("Please select an user", resourceCulture);
            }
        }
    }
}
